### ISSUE TITLE
Farming Cluster Support

### ISSUE THREAD

**Issue by vexr** [oula-network/autonomys#2]
Now that it has been rebased to gemini-3h-2024-jul-29 will there be support for GPU plotting in farming cluster?

**Comment by oula007** [comment]
[Supported](https://github.com/oula-network/subspace/releases/tag/v0.2.1)

**Comment by vexr** [comment]
Are there any other parameters required for GPU plotting with Farming Cluster? I can set the GPU by configuring the environment variables, and it appears to execute on that GPU, but the GPU plotter itself doesn't run.

export CUDA_VISIBLE_DEVICES=1 GPU_CONCURRENCY=15
subspace-farmer cluster --nats-server nats://nats01:4222 plotter --record-encoding-concurrency 32

<img width="1413" alt="Screenshot 2024-08-26 at 4 24 45 PM" src="https://github.com/user-attachments/assets/a9c7832a-03e4-4704-adb4-59e5a01db6a0">

**Comment by oula007** [comment]
Outdated issue.

**Comment by oula007** [comment]
Outdated issue.
